version: '3.8'

services:
  api01: &api
    image: robertoseba/rinha_nest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=rinha
      - DB_PASSWORD=123
      - DB_USER=admin
      - DB_POOL_SIZE=5
      - DB_PORT=5432
      - PORT=3000
    ports:
      - '3000:3000'
    #   - '9229:9229'
    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://api01:3000/clientes/1/extrato']
      interval: 2s
      retries: 10
      start_period: 10s
      start_interval: 1s

  api02:
    <<: *api
    hostname: api02
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://api02:3000/clientes/1/extrato']
      interval: 2s
      retries: 10
      start_period: 10s
      start_interval: 1s
    ports:
      - '3001:3000'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - '5432:5432'
    command: |
      postgres
      -c max_connections=100
      -c log_min_messages='panic'
      -c log_min_error_statement='panic'
      -c checkpoint_timeout=600 
      -c synchronous_commit=off
      -c fsync=off
      -c full_page_writes=off
      -c shared_buffers=75MB
      -c effective_cache_size=225MB
      -c maintenance_work_mem=19200kB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=2304kB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=64MB
      -c huge_pages=off
      -c min_wal_size=2GB
      -c max_wal_size=8GB
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '300MB'
    healthcheck:
      test: ['CMD', 'pg_isready', '--username', 'admin', '-d', 'rinha']
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 1s

  # warmup:
  #   hostname: warmup
  #   container_name: warmup
  #   network_mode: host
  #   image: fedora:39
  #   command: |
  #     /bin/bash -c "echo 'warmuping'; sleep 5;
  #       for i in $(seq 1 50);
  #       do echo -n '.' ;
  #       curl -s -X GET http://localhost:9999/clientes/5/extrato > /dev/null  &
  #     done; echo 'warmup done';"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.02"
  #         memory: "16MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
